"""Add 'country' field for users

Revision ID: 5a1d6c259f5b
Revises: cebc33afa416
Create Date: 2022-07-10 22:53:42.838161

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a1d6c259f5b'
down_revision = 'cebc33afa416'
branch_labels = None
depends_on = None


def upgrade():
    countries = postgresql.ENUM('ru', 'eu', 'us', name='countries')
    countries.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.Enum('ru', 'eu', 'us', name='countries'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
    countries = postgresql.ENUM('ru', 'eu', 'us', name='countries')
    countries.drop(op.get_bind())
