"""Move 'auth type' field from user table to 'social name' in socialaccount table

Revision ID: cebc33afa416
Revises: 958ad294ea3e
Create Date: 2022-07-10 15:50:58.508334

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cebc33afa416'
down_revision = '958ad294ea3e'
branch_labels = None
depends_on = None


def upgrade():
    socialname = postgresql.ENUM('google', name='socialname')
    socialname.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_users', sa.Column('social_name', sa.Enum('google', name='socialname'), nullable=False))
    op.create_unique_constraint(None, 'social_users', ['id'])
    op.drop_column('users', 'auth_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column(
            'auth_type', postgresql.ENUM(
            'default', 'google', name='authtype',
            ), autoincrement=False, nullable=False,
        ),
    )
    op.drop_constraint(None, 'social_users', type_='unique')
    op.drop_column('social_users', 'social_name')
    # ### end Alembic commands ###
    socialname = postgresql.ENUM('google', name='socialname')
    socialname.drop(op.get_bind())
